### ISSUE TITLE
[2] - Add Hero Banner to Home page

### ISSUE THREAD

**Issue by Potato-29** [Potato-29/turf-booking-site#2]
Currently the home page has a red background and nothing else, I would like it if you can find a good image / create one and add that as the Hero banner

**Comment by harsh0728** [comment]
@Potato-29 Yes I can do this I will solve this issue Assign this issue to me

**Comment by Potato-29** [comment]
@harsh0728, assigned! please provide a screenshot once you finish the changes

**Comment by atik-7866** [comment]
i too wanna work on this project do assign me any other issue if possible @Potato-29

**Comment by Potato-29** [comment]
Hey @atik-7866, please star the repo to stay updated, I'll be adding new issues to work on soon. Thanks for your interest:)

**Comment by harsh0728** [comment]
![Uploading localhost-3000-10-01-2024_04_41_PM.png…]()
Is this image okay 
Would I make this final

**Comment by Potato-29** [comment]
@harsh0728, i can't see your image, I think it was not completely uploaded

**Comment by harsh0728** [comment]
https://drive.google.com/file/d/1rmWO8cSP-vn5wyKbQOEF1M8rZYPJp6Aj/view?usp=sharing

**Comment by harsh0728** [comment]
this is okay the page is responsive as well and its looking good as compared to before 
https://drive.google.com/file/d/1awRFkC3PjbBphTdZWfoyOg6A4b26aAqz/view?usp=sharing

**Comment by harsh0728** [comment]
@Potato-29 I request you to please add the hactoberfest topic to the repository or add the hactoberfest-accepted label to my PR/MR
